apiVersion: apps/v1
kind: Deployment
metadata:
  name: results-app-deployment
  labels:
    app: results-app-demo
    tier: front-end
spec:
  template:
    metadata:
      name: results-app-pod
      labels:
        app: demo-voting-app
        name: results-app-front-end
        tier: front-end
    spec:
      containers:
        - name: results-app-container
          image: dockersamples/examplevotingapp_result
          ports:
            - containerPort: 80
  replicas: 2
  selector:
    matchLabels:
      app: demo-voting-app
      name: results-app-front-end