apiVersion: apps/v1
kind: Deployment
metadata:
  name: voting-app-deployment
  labels:
    app: voting-app-demo
    tier: front-end
spec:
  template:
    metadata:
      name: voting-app-pod
      labels:
        app: demo-voting-app
        name: voting-app-front-end
        tier: front-end
    spec:
      containers:
        - name: voting-app-container
          image: dockersamples/examplevotingapp_vote
          ports:
            - containerPort: 80
  replicas: 3
  selector:
    matchLabels:
      app: demo-voting-app
      name: voting-app-front-end