apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-app-deployment
  labels:
    app: worker-app
    tier: api
spec:
  template:
    metadata:
      name: worker-app-pod
      labels:
        app: demo-voting-app
        name: worker-api
        tier: api
    spec:
      containers:
        - name: worker-app-container
          image: dockersamples/examplevotingapp_worker
  replicas: 2
  selector:
    matchLabels:
      app: demo-voting-app
      name: worker-api