apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    app: demo-voting-app
spec:
  ports:
    - targetPort: 5432
      port: 5432
  selector:
    app: demo-voting-app
    name: postgres-db