apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    app: demo-voting-app
spec:
  type: ClusterIP
  ports:
    - targetPort: 6379
      port: 6379
  selector:
    app: demo-voting-app
    name: redis-db