apiVersion: v1
kind: Service
metadata:
  name: results-app-external-service
spec:
  type: LoadBalancer    
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: demo-voting-app
    name: results-app-front-end
