apiVersion: v1
kind: Service
metadata:
  name: results-app-external-service
spec:
  type: NodePort
  ports:
    - nodePort: 30010
      port: 80
      targetPort: 80
  selector:
    app: demo-voting-app
    name: results-app-front-end
