apiVersion: v1
kind: Service
metadata:
  name: voting-app-external-service
spec:
  type: NodePort
  ports:
    - nodePort: 30009
      port: 80
      targetPort: 80
  selector:
    app: demo-voting-app
    name: voting-app-front-end